### ISSUE TITLE
missing requirement on console/version from lib/console.rb

### ISSUE THREAD

**Issue by boutil** [socketry/console#13]
Hi,

`spec/console_spec.rb` tries to read the version number by requiring 'console'. However, 'lib/console.rb' (nor any other file under lib) does not read lib/console/version.rb.

Would it be sensible to add a `require_relative "console/version"` in 'lib/console.rb'?

**Comment by ioquatix** [comment]
Yes, that is sensible, thanks for asking. PR welcome.

**Comment by boutil** [comment]
thanks I've just created https://github.com/socketry/console/pull/14.

**Comment by ioquatix** [comment]
Thanks!
