### ISSUE TITLE
Whats the recommended way of switching logger outputs?

### ISSUE THREAD

**Issue by fnordfish** [socketry/console#20]
I'm pretty happy with the default logger, but would like to be able to switch over to "JSON lines in logfile" via user input (CLI switch or ENV var)

All my code basically ether uses `Console.logger.info(self, "Message")` directly, or includes the Console Module.

I couldn't figure out a "simple"/"nice" way of switching the output used by the default logger to something like `Console::Serialized::Logger`. Should I, instead of using `Console.logger`, build my own `ApplicationLogger` and re-implement `Console` and `Console::Logger` to make it switch the output?

**Comment by ioquatix** [comment]
There is a plan to automatically switch to JSON output when the attached $stderr is not a TTY. What do you think?

I would say this would be a nice "convention over configuration" but I can see how in some cases it might also be a problem.

For logging, my gut feeling is that we need to configure this using ENV variables. The reason for this is we don't always have the ability to inject configuration into an app, e.g. you don't want to add command line arguments for the full features of Console (log filtering by class, by level, etc).

So, my gut feeling is, either we adopt the above TTY detection, but allow a user to override it explicitly, e.g. `CONSOLE_FORMAT=XTerm` or `CONSOLE_FORMAT=JSON`. What do you think?

**Comment by fnordfish** [comment]
I'd go with the ENV var option - but that's me having a preference for explicit configurations over magic :)

**Comment by fnordfish** [comment]
I'd even suggest adding a `CONSOLE_OUT=/path/to/file` `CONSOLE_OUT=-` to overwrite the default `$stderr`.
This would make setting those quite intuitive `CONSOLE_OUT=/path/to/file CONSOLE_FORMAT=JSON` vs. `CONSOLE_OUT=/dev/stdout`

At which point I would add some magic, by making the format discoverable: Having `CONSOLE_FORMAT=JSON` would try to load a `Console::Format:Json` and call that, so I could simply define my own `Console::Format::Msgpack` (or some other custom format), or even overwrite Json to use Oj in some special config.

**Comment by ioquatix** [comment]
Merged, thank you for your contribution.
