### ISSUE TITLE
Support for `CONSOLE_OFF=` and `CONSOLE_ALL=`?

### ISSUE THREAD

**Issue by fnordfish** [socketry/console#21]
Basically, `CONSOLE_<LEVEL>` with the special level "off" and "all".
It would be helpful to be able to focus on some logging subjects, while silencing others.

```console
$ CONSOLE_LEVEL=error CONSOLE_ALL=Focus::Class CONSOLE_OFF=Not::Interested::Class ./machine
```

would print everything from `Focus::Class`, nothing from `Not::Interested::Class` and errors and above from everything else.

While "all" would just be a convenience for the build in "info", "off" - as far as I can tell - is currently not possible to set via env vars.

**Comment by ioquatix** [comment]
This seems reasonable to me.

**Comment by ioquatix** [comment]
Merged, thank you for your contribution.
