### ISSUE TITLE
tags for 1.15.1, 1.15.2 and 1.15.3

### ISSUE THREAD

**Issue by henrich** [socketry/console#29]
https://rubygems.org/gems/console/versions says it has 1.15.1, 1.15.2 and 1.15.3 but there are [no such tags](https://github.com/socketry/console/tags). Could you push it, please?

**Comment by ioquatix** [comment]
Thanks for pointing that out, I've pushed the tags. This was fixed in the gem release process already so it shouldn't be a problem going forward.

**Comment by h-yamane-sti** [comment]
Thanks!

**Comment by henrich** [comment]
Thanks!
