### ISSUE TITLE
Delay when writing

### ISSUE THREAD

**Issue by wtn** [socketry/console#33]
I'm manually configuring my logger to write to a file as follows:
``` ruby
class MyServer
  Console.logger = Console::Logger.new \
    Console::Serialized::Logger.new(File.open Rails.root.join('log', "#{name.underscore}.#{Rails.env}.log"), ?a)

  extend Console
  logger.info "#{name} loaded"
end
```

The logger collects messages as expected, but they aren't written to disk until the process exits.

**Comment by ioquatix** [comment]
Files are buffered by default. For logging you should probably use `sync=true` output.

**Comment by wtn** [comment]
Thank you, that works!
