### ISSUE TITLE
Ruby version compatibility

### ISSUE THREAD

**Issue by pvande** [socketry/console#35]
Recent changes ([this one](https://github.com/socketry/console/commit/4576cf0b0ee1b4862b143997a02802b9448f8b31#diff-c12842e84abe566fa563691db226405df5f6ef483945834884296a2b8bf5eae7L76-R77) in particular, perhaps others) have broken compatibility with older Ruby versions (notably, pre 2.7). This is in conflict with the gemspec, which indicates compatibility with Ruby 2.5+.

**Comment by ioquatix** [comment]
Thanks for letting me know, I'll fix this.

**Comment by ioquatix** [comment]
I'm not testing further back than 2.7.0 - I apologies this may have caused some problems for you. So, for now, if you are using Ruby < 2.7 I recommend pin to `~> 1.5.0`.

I might yank the 1.6.0 and 1.6.1 releases.

**Comment by ioquatix** [comment]
Okay, yanking done, 1.16.0 and 1.16.1 are gone, and https://rubygems.org/gems/console/versions/1.16.2 requires >= 2.7.

Hope this addresses the issue.

**Comment by pvande** [comment]
The issue only ever manifested in our CI system, thankfully. Our dependency on `console` is transient (through `async`), so pinning the version would require us to introduce a direct dependency on `console`.

Updating the version requirement has resolved the issue. Thank you for the prompt response!

**Comment by ahorek** [comment]
it still breaks on ruby 2.7.0 - 2.7.2
https://github.com/socketry/console/blob/main/lib/console/progress.rb#L76

<pre>
@output.info(@subject, ...)
syntax error, unexpected end-of-input, expecting `end'
</pre>

the new syntax is fully supported since ruby 2.7.3

**Comment by ioquatix** [comment]
@ahorek thanks, I didn't know it. I'll set the minimum version to be 2.7.3.

Thanks!
