### ISSUE TITLE
Syntax error on version 1.16.2

### ISSUE THREAD

**Issue by Trehana** [socketry/console#39]
When updated to version 1.16.2 along with Async gem the following error occurs

Uncaught exception: /Users/trehannaf/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'
			@output.info(@subject, ...)
<img width="1022" alt="console-error" src="https://user-images.githubusercontent.com/7446470/207316558-f403831e-8932-4d10-96df-3428b5756adb.png">

**Comment by ioquatix** [comment]
Make sure you are using the latest version of Ruby 2.7.3+
