### ISSUE TITLE
Console::Filter changes output verbosity

### ISSUE THREAD

**Issue by bryanp** [socketry/console#6]
I'm not 100% certain this is a bug, but it's having some unintended consequences in my project and I wanted to start a discussion. When initialized, `Console::Filter` sets its own verbosity and also the verbosity of its output:

```ruby
def verbose!(value = true)
  @verbose = value
  @output.verbose!(value)
end
```

In my case, a single output is shared among many filters; a new filter instance is created for every request and the output is a shared object that's created once and shared across the filters. 

Why does `Console::Filter` change the verbosity of the output? Shouldn't that responsibility fall to the end user? In my case I'd like to freeze the shared output instance to guarantee it won't change, but I can't because every filter tries to mutate the output instance.

FWIW commenting out `@output.verbose!(value)` doesn't break any tests.

Curious your thoughts here @ioquatix.

**Comment by ioquatix** [comment]
Can you use `Filter#verbose=`?

**Comment by bryanp** [comment]
I don’t follow... `verbose!` is being called on the output for me. I’d rather initialize the filter and it not mutate state I pass to it.

**Comment by ioquatix** [comment]
I see...

https://github.com/socketry/console/blob/master/lib/console/filter.rb#L70

Yeah we could probably change this.

**Comment by bryanp** [comment]
Yeah, can we just remove this line? 

* https://github.com/socketry/console/blob/master/lib/console/filter.rb#L99

It doesn't break any tests.

**Comment by ioquatix** [comment]
The point of `verbose!` is to pass it through all outputs recursively.

If you don't want that behaviour, it should use `verbose = true`. But this problem is created by the constructor.

Did you override `verbose!`?

**Comment by bryanp** [comment]
Would it be appropriate to change the constructor so that it doesn't call `verbose!`?

**Comment by ioquatix** [comment]
Yes, it doesn't make that much sense for the constructor to call it.

What do you think of the proposed changes for 1.6.0?

**Comment by bryanp** [comment]
Got it. I think https://github.com/socketry/console/commit/076ed93eb3975bc615f3f145316f21cd11e643b3 solves my particular issue, and makes more sense overall.

**Comment by ioquatix** [comment]
Okay I released it and also updated the documentation.

**Comment by ioquatix** [comment]
If you have time do you want to submit a PR to ensure that a longer doesn't mutate the output?
