### ISSUE TITLE
Inconsistent return values based on Output used

### ISSUE THREAD

**Issue by fnordfish** [socketry/console#64]
`Console.info` etc. will return different values based on the output used.

The serialized (Json) logger will return `nil`:
https://github.com/socketry/console/blob/ebd30eca2797b448a791d2e4149b1f1b56db7207/lib/console/output/serialized.rb#L71

The terminal logger will return the bytes written:
https://github.com/socketry/console/blob/ebd30eca2797b448a791d2e4149b1f1b56db7207/lib/console/output/terminal.rb#L137

The split logger will return an Array of used Loggers:
https://github.com/socketry/console/blob/ebd30eca2797b448a791d2e4149b1f1b56db7207/lib/console/output/split.rb#L22-L24

It would be nice if they could all return a consistent value. Probably either `nil` (like `puts`) or `true` like `::Logger`.

**Comment by ioquatix** [comment]
Released in `v1.29.2` - always return nil.
